### ISSUE TITLE
Oracle License Agreement Compliance

### ISSUE THREAD

**Issue by ChristopherDavenport** [ericallen/banner-xe-docker#1]
While I too am endeavoring to create a more inclusive open-source environment for the banner community. I wanted to make you aware that technically you have included the ojdbc6.jar which has a very strict [license agreement](http://www.oracle.com/technetwork/licenses/distribution-license-152002.html). General terms are to direct individuals or walk them through the inclusion of such files because each individual who has access either needs to directly included or to have in some for accepted the terms.

I hate to be a downer, I just want to make sure you were aware before someone came knocking.

**Comment by ericallen** [comment]
Thanks for pointing it out.  They have been merged in. I will push new builds to the hub shorter.
